// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orders

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID     int32
	UserID int64
	Status string
}

type OrderItem struct {
	ID      int32
	OrderID int64
	Sku     int32
	Count   int32
}

type OutboxOrderEvent struct {
	ID        int32
	OrderID   int64
	EventType string
	WasSent   bool
	CreatedAt pgtype.Timestamptz
}

type Stock struct {
	ID         int32
	Sku        int32
	TotalCount int32
	Reserved   int32
}
