// Code generated by http://github.com/gojuno/minimock (v3.3.11). DO NOT EDIT.

package mock

//go:generate minimock -i route256/cart/internal/service/cart/list.productService -o product_service_mock.go -n ProductServiceMock -p mock

import (
	"context"
	"route256/cart/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProductServiceMock implements list.productService
type ProductServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetProductInfo          func(ctx context.Context, sku uint32) (pp1 *domain.Product, err error)
	inspectFuncGetProductInfo   func(ctx context.Context, sku uint32)
	afterGetProductInfoCounter  uint64
	beforeGetProductInfoCounter uint64
	GetProductInfoMock          mProductServiceMockGetProductInfo
}

// NewProductServiceMock returns a mock for list.productService
func NewProductServiceMock(t minimock.Tester) *ProductServiceMock {
	m := &ProductServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetProductInfoMock = mProductServiceMockGetProductInfo{mock: m}
	m.GetProductInfoMock.callArgs = []*ProductServiceMockGetProductInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProductServiceMockGetProductInfo struct {
	optional           bool
	mock               *ProductServiceMock
	defaultExpectation *ProductServiceMockGetProductInfoExpectation
	expectations       []*ProductServiceMockGetProductInfoExpectation

	callArgs []*ProductServiceMockGetProductInfoParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// ProductServiceMockGetProductInfoExpectation specifies expectation struct of the productService.GetProductInfo
type ProductServiceMockGetProductInfoExpectation struct {
	mock      *ProductServiceMock
	params    *ProductServiceMockGetProductInfoParams
	paramPtrs *ProductServiceMockGetProductInfoParamPtrs
	results   *ProductServiceMockGetProductInfoResults
	Counter   uint64
}

// ProductServiceMockGetProductInfoParams contains parameters of the productService.GetProductInfo
type ProductServiceMockGetProductInfoParams struct {
	ctx context.Context
	sku uint32
}

// ProductServiceMockGetProductInfoParamPtrs contains pointers to parameters of the productService.GetProductInfo
type ProductServiceMockGetProductInfoParamPtrs struct {
	ctx *context.Context
	sku *uint32
}

// ProductServiceMockGetProductInfoResults contains results of the productService.GetProductInfo
type ProductServiceMockGetProductInfoResults struct {
	pp1 *domain.Product
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Optional() *mProductServiceMockGetProductInfo {
	mmGetProductInfo.optional = true
	return mmGetProductInfo
}

// Expect sets up expected params for productService.GetProductInfo
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Expect(ctx context.Context, sku uint32) *mProductServiceMockGetProductInfo {
	if mmGetProductInfo.mock.funcGetProductInfo != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Set")
	}

	if mmGetProductInfo.defaultExpectation == nil {
		mmGetProductInfo.defaultExpectation = &ProductServiceMockGetProductInfoExpectation{}
	}

	if mmGetProductInfo.defaultExpectation.paramPtrs != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by ExpectParams functions")
	}

	mmGetProductInfo.defaultExpectation.params = &ProductServiceMockGetProductInfoParams{ctx, sku}
	for _, e := range mmGetProductInfo.expectations {
		if minimock.Equal(e.params, mmGetProductInfo.defaultExpectation.params) {
			mmGetProductInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProductInfo.defaultExpectation.params)
		}
	}

	return mmGetProductInfo
}

// ExpectCtxParam1 sets up expected param ctx for productService.GetProductInfo
func (mmGetProductInfo *mProductServiceMockGetProductInfo) ExpectCtxParam1(ctx context.Context) *mProductServiceMockGetProductInfo {
	if mmGetProductInfo.mock.funcGetProductInfo != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Set")
	}

	if mmGetProductInfo.defaultExpectation == nil {
		mmGetProductInfo.defaultExpectation = &ProductServiceMockGetProductInfoExpectation{}
	}

	if mmGetProductInfo.defaultExpectation.params != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Expect")
	}

	if mmGetProductInfo.defaultExpectation.paramPtrs == nil {
		mmGetProductInfo.defaultExpectation.paramPtrs = &ProductServiceMockGetProductInfoParamPtrs{}
	}
	mmGetProductInfo.defaultExpectation.paramPtrs.ctx = &ctx

	return mmGetProductInfo
}

// ExpectSkuParam2 sets up expected param sku for productService.GetProductInfo
func (mmGetProductInfo *mProductServiceMockGetProductInfo) ExpectSkuParam2(sku uint32) *mProductServiceMockGetProductInfo {
	if mmGetProductInfo.mock.funcGetProductInfo != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Set")
	}

	if mmGetProductInfo.defaultExpectation == nil {
		mmGetProductInfo.defaultExpectation = &ProductServiceMockGetProductInfoExpectation{}
	}

	if mmGetProductInfo.defaultExpectation.params != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Expect")
	}

	if mmGetProductInfo.defaultExpectation.paramPtrs == nil {
		mmGetProductInfo.defaultExpectation.paramPtrs = &ProductServiceMockGetProductInfoParamPtrs{}
	}
	mmGetProductInfo.defaultExpectation.paramPtrs.sku = &sku

	return mmGetProductInfo
}

// Inspect accepts an inspector function that has same arguments as the productService.GetProductInfo
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Inspect(f func(ctx context.Context, sku uint32)) *mProductServiceMockGetProductInfo {
	if mmGetProductInfo.mock.inspectFuncGetProductInfo != nil {
		mmGetProductInfo.mock.t.Fatalf("Inspect function is already set for ProductServiceMock.GetProductInfo")
	}

	mmGetProductInfo.mock.inspectFuncGetProductInfo = f

	return mmGetProductInfo
}

// Return sets up results that will be returned by productService.GetProductInfo
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Return(pp1 *domain.Product, err error) *ProductServiceMock {
	if mmGetProductInfo.mock.funcGetProductInfo != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Set")
	}

	if mmGetProductInfo.defaultExpectation == nil {
		mmGetProductInfo.defaultExpectation = &ProductServiceMockGetProductInfoExpectation{mock: mmGetProductInfo.mock}
	}
	mmGetProductInfo.defaultExpectation.results = &ProductServiceMockGetProductInfoResults{pp1, err}
	return mmGetProductInfo.mock
}

// Set uses given function f to mock the productService.GetProductInfo method
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Set(f func(ctx context.Context, sku uint32) (pp1 *domain.Product, err error)) *ProductServiceMock {
	if mmGetProductInfo.defaultExpectation != nil {
		mmGetProductInfo.mock.t.Fatalf("Default expectation is already set for the productService.GetProductInfo method")
	}

	if len(mmGetProductInfo.expectations) > 0 {
		mmGetProductInfo.mock.t.Fatalf("Some expectations are already set for the productService.GetProductInfo method")
	}

	mmGetProductInfo.mock.funcGetProductInfo = f
	return mmGetProductInfo.mock
}

// When sets expectation for the productService.GetProductInfo which will trigger the result defined by the following
// Then helper
func (mmGetProductInfo *mProductServiceMockGetProductInfo) When(ctx context.Context, sku uint32) *ProductServiceMockGetProductInfoExpectation {
	if mmGetProductInfo.mock.funcGetProductInfo != nil {
		mmGetProductInfo.mock.t.Fatalf("ProductServiceMock.GetProductInfo mock is already set by Set")
	}

	expectation := &ProductServiceMockGetProductInfoExpectation{
		mock:   mmGetProductInfo.mock,
		params: &ProductServiceMockGetProductInfoParams{ctx, sku},
	}
	mmGetProductInfo.expectations = append(mmGetProductInfo.expectations, expectation)
	return expectation
}

// Then sets up productService.GetProductInfo return parameters for the expectation previously defined by the When method
func (e *ProductServiceMockGetProductInfoExpectation) Then(pp1 *domain.Product, err error) *ProductServiceMock {
	e.results = &ProductServiceMockGetProductInfoResults{pp1, err}
	return e.mock
}

// Times sets number of times productService.GetProductInfo should be invoked
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Times(n uint64) *mProductServiceMockGetProductInfo {
	if n == 0 {
		mmGetProductInfo.mock.t.Fatalf("Times of ProductServiceMock.GetProductInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProductInfo.expectedInvocations, n)
	return mmGetProductInfo
}

func (mmGetProductInfo *mProductServiceMockGetProductInfo) invocationsDone() bool {
	if len(mmGetProductInfo.expectations) == 0 && mmGetProductInfo.defaultExpectation == nil && mmGetProductInfo.mock.funcGetProductInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProductInfo.mock.afterGetProductInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProductInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProductInfo implements list.productService
func (mmGetProductInfo *ProductServiceMock) GetProductInfo(ctx context.Context, sku uint32) (pp1 *domain.Product, err error) {
	mm_atomic.AddUint64(&mmGetProductInfo.beforeGetProductInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProductInfo.afterGetProductInfoCounter, 1)

	if mmGetProductInfo.inspectFuncGetProductInfo != nil {
		mmGetProductInfo.inspectFuncGetProductInfo(ctx, sku)
	}

	mm_params := ProductServiceMockGetProductInfoParams{ctx, sku}

	// Record call args
	mmGetProductInfo.GetProductInfoMock.mutex.Lock()
	mmGetProductInfo.GetProductInfoMock.callArgs = append(mmGetProductInfo.GetProductInfoMock.callArgs, &mm_params)
	mmGetProductInfo.GetProductInfoMock.mutex.Unlock()

	for _, e := range mmGetProductInfo.GetProductInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetProductInfo.GetProductInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProductInfo.GetProductInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProductInfo.GetProductInfoMock.defaultExpectation.params
		mm_want_ptrs := mmGetProductInfo.GetProductInfoMock.defaultExpectation.paramPtrs

		mm_got := ProductServiceMockGetProductInfoParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetProductInfo.t.Errorf("ProductServiceMock.GetProductInfo got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmGetProductInfo.t.Errorf("ProductServiceMock.GetProductInfo got unexpected parameter sku, want: %#v, got: %#v%s\n", *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProductInfo.t.Errorf("ProductServiceMock.GetProductInfo got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProductInfo.GetProductInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProductInfo.t.Fatal("No results are set for the ProductServiceMock.GetProductInfo")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetProductInfo.funcGetProductInfo != nil {
		return mmGetProductInfo.funcGetProductInfo(ctx, sku)
	}
	mmGetProductInfo.t.Fatalf("Unexpected call to ProductServiceMock.GetProductInfo. %v %v", ctx, sku)
	return
}

// GetProductInfoAfterCounter returns a count of finished ProductServiceMock.GetProductInfo invocations
func (mmGetProductInfo *ProductServiceMock) GetProductInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProductInfo.afterGetProductInfoCounter)
}

// GetProductInfoBeforeCounter returns a count of ProductServiceMock.GetProductInfo invocations
func (mmGetProductInfo *ProductServiceMock) GetProductInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProductInfo.beforeGetProductInfoCounter)
}

// Calls returns a list of arguments used in each call to ProductServiceMock.GetProductInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProductInfo *mProductServiceMockGetProductInfo) Calls() []*ProductServiceMockGetProductInfoParams {
	mmGetProductInfo.mutex.RLock()

	argCopy := make([]*ProductServiceMockGetProductInfoParams, len(mmGetProductInfo.callArgs))
	copy(argCopy, mmGetProductInfo.callArgs)

	mmGetProductInfo.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductInfoDone returns true if the count of the GetProductInfo invocations corresponds
// the number of defined expectations
func (m *ProductServiceMock) MinimockGetProductInfoDone() bool {
	if m.GetProductInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProductInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProductInfoMock.invocationsDone()
}

// MinimockGetProductInfoInspect logs each unmet expectation
func (m *ProductServiceMock) MinimockGetProductInfoInspect() {
	for _, e := range m.GetProductInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProductServiceMock.GetProductInfo with params: %#v", *e.params)
		}
	}

	afterGetProductInfoCounter := mm_atomic.LoadUint64(&m.afterGetProductInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductInfoMock.defaultExpectation != nil && afterGetProductInfoCounter < 1 {
		if m.GetProductInfoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ProductServiceMock.GetProductInfo")
		} else {
			m.t.Errorf("Expected call to ProductServiceMock.GetProductInfo with params: %#v", *m.GetProductInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProductInfo != nil && afterGetProductInfoCounter < 1 {
		m.t.Error("Expected call to ProductServiceMock.GetProductInfo")
	}

	if !m.GetProductInfoMock.invocationsDone() && afterGetProductInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to ProductServiceMock.GetProductInfo but found %d calls",
			mm_atomic.LoadUint64(&m.GetProductInfoMock.expectedInvocations), afterGetProductInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProductServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetProductInfoInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProductServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProductServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetProductInfoDone()
}
