// Code generated by http://github.com/gojuno/minimock (v3.3.11). DO NOT EDIT.

package mock

//go:generate minimock -i route256/loms/internal/service/loms.StocksRepository -o stocks_repository_mock.go -n StocksRepositoryMock -p mock

import (
	"context"
	"route256/loms/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// StocksRepositoryMock implements lomsusecase.StocksRepository
type StocksRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetBySKU          func(ctx context.Context, sku uint32) (ip1 *int64, err error)
	inspectFuncGetBySKU   func(ctx context.Context, sku uint32)
	afterGetBySKUCounter  uint64
	beforeGetBySKUCounter uint64
	GetBySKUMock          mStocksRepositoryMockGetBySKU

	funcReserve          func(ctx context.Context, items []domain.Item) (err error)
	inspectFuncReserve   func(ctx context.Context, items []domain.Item)
	afterReserveCounter  uint64
	beforeReserveCounter uint64
	ReserveMock          mStocksRepositoryMockReserve

	funcReserveCancel          func(ctx context.Context, items []domain.Item) (err error)
	inspectFuncReserveCancel   func(ctx context.Context, items []domain.Item)
	afterReserveCancelCounter  uint64
	beforeReserveCancelCounter uint64
	ReserveCancelMock          mStocksRepositoryMockReserveCancel

	funcReserveRemove          func(ctx context.Context, items []domain.Item) (err error)
	inspectFuncReserveRemove   func(ctx context.Context, items []domain.Item)
	afterReserveRemoveCounter  uint64
	beforeReserveRemoveCounter uint64
	ReserveRemoveMock          mStocksRepositoryMockReserveRemove
}

// NewStocksRepositoryMock returns a mock for lomsusecase.StocksRepository
func NewStocksRepositoryMock(t minimock.Tester) *StocksRepositoryMock {
	m := &StocksRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetBySKUMock = mStocksRepositoryMockGetBySKU{mock: m}
	m.GetBySKUMock.callArgs = []*StocksRepositoryMockGetBySKUParams{}

	m.ReserveMock = mStocksRepositoryMockReserve{mock: m}
	m.ReserveMock.callArgs = []*StocksRepositoryMockReserveParams{}

	m.ReserveCancelMock = mStocksRepositoryMockReserveCancel{mock: m}
	m.ReserveCancelMock.callArgs = []*StocksRepositoryMockReserveCancelParams{}

	m.ReserveRemoveMock = mStocksRepositoryMockReserveRemove{mock: m}
	m.ReserveRemoveMock.callArgs = []*StocksRepositoryMockReserveRemoveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStocksRepositoryMockGetBySKU struct {
	optional           bool
	mock               *StocksRepositoryMock
	defaultExpectation *StocksRepositoryMockGetBySKUExpectation
	expectations       []*StocksRepositoryMockGetBySKUExpectation

	callArgs []*StocksRepositoryMockGetBySKUParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// StocksRepositoryMockGetBySKUExpectation specifies expectation struct of the StocksRepository.GetBySKU
type StocksRepositoryMockGetBySKUExpectation struct {
	mock      *StocksRepositoryMock
	params    *StocksRepositoryMockGetBySKUParams
	paramPtrs *StocksRepositoryMockGetBySKUParamPtrs
	results   *StocksRepositoryMockGetBySKUResults
	Counter   uint64
}

// StocksRepositoryMockGetBySKUParams contains parameters of the StocksRepository.GetBySKU
type StocksRepositoryMockGetBySKUParams struct {
	ctx context.Context
	sku uint32
}

// StocksRepositoryMockGetBySKUParamPtrs contains pointers to parameters of the StocksRepository.GetBySKU
type StocksRepositoryMockGetBySKUParamPtrs struct {
	ctx *context.Context
	sku *uint32
}

// StocksRepositoryMockGetBySKUResults contains results of the StocksRepository.GetBySKU
type StocksRepositoryMockGetBySKUResults struct {
	ip1 *int64
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Optional() *mStocksRepositoryMockGetBySKU {
	mmGetBySKU.optional = true
	return mmGetBySKU
}

// Expect sets up expected params for StocksRepository.GetBySKU
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Expect(ctx context.Context, sku uint32) *mStocksRepositoryMockGetBySKU {
	if mmGetBySKU.mock.funcGetBySKU != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Set")
	}

	if mmGetBySKU.defaultExpectation == nil {
		mmGetBySKU.defaultExpectation = &StocksRepositoryMockGetBySKUExpectation{}
	}

	if mmGetBySKU.defaultExpectation.paramPtrs != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by ExpectParams functions")
	}

	mmGetBySKU.defaultExpectation.params = &StocksRepositoryMockGetBySKUParams{ctx, sku}
	for _, e := range mmGetBySKU.expectations {
		if minimock.Equal(e.params, mmGetBySKU.defaultExpectation.params) {
			mmGetBySKU.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetBySKU.defaultExpectation.params)
		}
	}

	return mmGetBySKU
}

// ExpectCtxParam1 sets up expected param ctx for StocksRepository.GetBySKU
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) ExpectCtxParam1(ctx context.Context) *mStocksRepositoryMockGetBySKU {
	if mmGetBySKU.mock.funcGetBySKU != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Set")
	}

	if mmGetBySKU.defaultExpectation == nil {
		mmGetBySKU.defaultExpectation = &StocksRepositoryMockGetBySKUExpectation{}
	}

	if mmGetBySKU.defaultExpectation.params != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Expect")
	}

	if mmGetBySKU.defaultExpectation.paramPtrs == nil {
		mmGetBySKU.defaultExpectation.paramPtrs = &StocksRepositoryMockGetBySKUParamPtrs{}
	}
	mmGetBySKU.defaultExpectation.paramPtrs.ctx = &ctx

	return mmGetBySKU
}

// ExpectSkuParam2 sets up expected param sku for StocksRepository.GetBySKU
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) ExpectSkuParam2(sku uint32) *mStocksRepositoryMockGetBySKU {
	if mmGetBySKU.mock.funcGetBySKU != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Set")
	}

	if mmGetBySKU.defaultExpectation == nil {
		mmGetBySKU.defaultExpectation = &StocksRepositoryMockGetBySKUExpectation{}
	}

	if mmGetBySKU.defaultExpectation.params != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Expect")
	}

	if mmGetBySKU.defaultExpectation.paramPtrs == nil {
		mmGetBySKU.defaultExpectation.paramPtrs = &StocksRepositoryMockGetBySKUParamPtrs{}
	}
	mmGetBySKU.defaultExpectation.paramPtrs.sku = &sku

	return mmGetBySKU
}

// Inspect accepts an inspector function that has same arguments as the StocksRepository.GetBySKU
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Inspect(f func(ctx context.Context, sku uint32)) *mStocksRepositoryMockGetBySKU {
	if mmGetBySKU.mock.inspectFuncGetBySKU != nil {
		mmGetBySKU.mock.t.Fatalf("Inspect function is already set for StocksRepositoryMock.GetBySKU")
	}

	mmGetBySKU.mock.inspectFuncGetBySKU = f

	return mmGetBySKU
}

// Return sets up results that will be returned by StocksRepository.GetBySKU
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Return(ip1 *int64, err error) *StocksRepositoryMock {
	if mmGetBySKU.mock.funcGetBySKU != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Set")
	}

	if mmGetBySKU.defaultExpectation == nil {
		mmGetBySKU.defaultExpectation = &StocksRepositoryMockGetBySKUExpectation{mock: mmGetBySKU.mock}
	}
	mmGetBySKU.defaultExpectation.results = &StocksRepositoryMockGetBySKUResults{ip1, err}
	return mmGetBySKU.mock
}

// Set uses given function f to mock the StocksRepository.GetBySKU method
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Set(f func(ctx context.Context, sku uint32) (ip1 *int64, err error)) *StocksRepositoryMock {
	if mmGetBySKU.defaultExpectation != nil {
		mmGetBySKU.mock.t.Fatalf("Default expectation is already set for the StocksRepository.GetBySKU method")
	}

	if len(mmGetBySKU.expectations) > 0 {
		mmGetBySKU.mock.t.Fatalf("Some expectations are already set for the StocksRepository.GetBySKU method")
	}

	mmGetBySKU.mock.funcGetBySKU = f
	return mmGetBySKU.mock
}

// When sets expectation for the StocksRepository.GetBySKU which will trigger the result defined by the following
// Then helper
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) When(ctx context.Context, sku uint32) *StocksRepositoryMockGetBySKUExpectation {
	if mmGetBySKU.mock.funcGetBySKU != nil {
		mmGetBySKU.mock.t.Fatalf("StocksRepositoryMock.GetBySKU mock is already set by Set")
	}

	expectation := &StocksRepositoryMockGetBySKUExpectation{
		mock:   mmGetBySKU.mock,
		params: &StocksRepositoryMockGetBySKUParams{ctx, sku},
	}
	mmGetBySKU.expectations = append(mmGetBySKU.expectations, expectation)
	return expectation
}

// Then sets up StocksRepository.GetBySKU return parameters for the expectation previously defined by the When method
func (e *StocksRepositoryMockGetBySKUExpectation) Then(ip1 *int64, err error) *StocksRepositoryMock {
	e.results = &StocksRepositoryMockGetBySKUResults{ip1, err}
	return e.mock
}

// Times sets number of times StocksRepository.GetBySKU should be invoked
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Times(n uint64) *mStocksRepositoryMockGetBySKU {
	if n == 0 {
		mmGetBySKU.mock.t.Fatalf("Times of StocksRepositoryMock.GetBySKU mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetBySKU.expectedInvocations, n)
	return mmGetBySKU
}

func (mmGetBySKU *mStocksRepositoryMockGetBySKU) invocationsDone() bool {
	if len(mmGetBySKU.expectations) == 0 && mmGetBySKU.defaultExpectation == nil && mmGetBySKU.mock.funcGetBySKU == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetBySKU.mock.afterGetBySKUCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetBySKU.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetBySKU implements lomsusecase.StocksRepository
func (mmGetBySKU *StocksRepositoryMock) GetBySKU(ctx context.Context, sku uint32) (ip1 *int64, err error) {
	mm_atomic.AddUint64(&mmGetBySKU.beforeGetBySKUCounter, 1)
	defer mm_atomic.AddUint64(&mmGetBySKU.afterGetBySKUCounter, 1)

	if mmGetBySKU.inspectFuncGetBySKU != nil {
		mmGetBySKU.inspectFuncGetBySKU(ctx, sku)
	}

	mm_params := StocksRepositoryMockGetBySKUParams{ctx, sku}

	// Record call args
	mmGetBySKU.GetBySKUMock.mutex.Lock()
	mmGetBySKU.GetBySKUMock.callArgs = append(mmGetBySKU.GetBySKUMock.callArgs, &mm_params)
	mmGetBySKU.GetBySKUMock.mutex.Unlock()

	for _, e := range mmGetBySKU.GetBySKUMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ip1, e.results.err
		}
	}

	if mmGetBySKU.GetBySKUMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetBySKU.GetBySKUMock.defaultExpectation.Counter, 1)
		mm_want := mmGetBySKU.GetBySKUMock.defaultExpectation.params
		mm_want_ptrs := mmGetBySKU.GetBySKUMock.defaultExpectation.paramPtrs

		mm_got := StocksRepositoryMockGetBySKUParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetBySKU.t.Errorf("StocksRepositoryMock.GetBySKU got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmGetBySKU.t.Errorf("StocksRepositoryMock.GetBySKU got unexpected parameter sku, want: %#v, got: %#v%s\n", *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetBySKU.t.Errorf("StocksRepositoryMock.GetBySKU got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetBySKU.GetBySKUMock.defaultExpectation.results
		if mm_results == nil {
			mmGetBySKU.t.Fatal("No results are set for the StocksRepositoryMock.GetBySKU")
		}
		return (*mm_results).ip1, (*mm_results).err
	}
	if mmGetBySKU.funcGetBySKU != nil {
		return mmGetBySKU.funcGetBySKU(ctx, sku)
	}
	mmGetBySKU.t.Fatalf("Unexpected call to StocksRepositoryMock.GetBySKU. %v %v", ctx, sku)
	return
}

// GetBySKUAfterCounter returns a count of finished StocksRepositoryMock.GetBySKU invocations
func (mmGetBySKU *StocksRepositoryMock) GetBySKUAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetBySKU.afterGetBySKUCounter)
}

// GetBySKUBeforeCounter returns a count of StocksRepositoryMock.GetBySKU invocations
func (mmGetBySKU *StocksRepositoryMock) GetBySKUBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetBySKU.beforeGetBySKUCounter)
}

// Calls returns a list of arguments used in each call to StocksRepositoryMock.GetBySKU.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetBySKU *mStocksRepositoryMockGetBySKU) Calls() []*StocksRepositoryMockGetBySKUParams {
	mmGetBySKU.mutex.RLock()

	argCopy := make([]*StocksRepositoryMockGetBySKUParams, len(mmGetBySKU.callArgs))
	copy(argCopy, mmGetBySKU.callArgs)

	mmGetBySKU.mutex.RUnlock()

	return argCopy
}

// MinimockGetBySKUDone returns true if the count of the GetBySKU invocations corresponds
// the number of defined expectations
func (m *StocksRepositoryMock) MinimockGetBySKUDone() bool {
	if m.GetBySKUMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetBySKUMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetBySKUMock.invocationsDone()
}

// MinimockGetBySKUInspect logs each unmet expectation
func (m *StocksRepositoryMock) MinimockGetBySKUInspect() {
	for _, e := range m.GetBySKUMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StocksRepositoryMock.GetBySKU with params: %#v", *e.params)
		}
	}

	afterGetBySKUCounter := mm_atomic.LoadUint64(&m.afterGetBySKUCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetBySKUMock.defaultExpectation != nil && afterGetBySKUCounter < 1 {
		if m.GetBySKUMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StocksRepositoryMock.GetBySKU")
		} else {
			m.t.Errorf("Expected call to StocksRepositoryMock.GetBySKU with params: %#v", *m.GetBySKUMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetBySKU != nil && afterGetBySKUCounter < 1 {
		m.t.Error("Expected call to StocksRepositoryMock.GetBySKU")
	}

	if !m.GetBySKUMock.invocationsDone() && afterGetBySKUCounter > 0 {
		m.t.Errorf("Expected %d calls to StocksRepositoryMock.GetBySKU but found %d calls",
			mm_atomic.LoadUint64(&m.GetBySKUMock.expectedInvocations), afterGetBySKUCounter)
	}
}

type mStocksRepositoryMockReserve struct {
	optional           bool
	mock               *StocksRepositoryMock
	defaultExpectation *StocksRepositoryMockReserveExpectation
	expectations       []*StocksRepositoryMockReserveExpectation

	callArgs []*StocksRepositoryMockReserveParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// StocksRepositoryMockReserveExpectation specifies expectation struct of the StocksRepository.Reserve
type StocksRepositoryMockReserveExpectation struct {
	mock      *StocksRepositoryMock
	params    *StocksRepositoryMockReserveParams
	paramPtrs *StocksRepositoryMockReserveParamPtrs
	results   *StocksRepositoryMockReserveResults
	Counter   uint64
}

// StocksRepositoryMockReserveParams contains parameters of the StocksRepository.Reserve
type StocksRepositoryMockReserveParams struct {
	ctx   context.Context
	items []domain.Item
}

// StocksRepositoryMockReserveParamPtrs contains pointers to parameters of the StocksRepository.Reserve
type StocksRepositoryMockReserveParamPtrs struct {
	ctx   *context.Context
	items *[]domain.Item
}

// StocksRepositoryMockReserveResults contains results of the StocksRepository.Reserve
type StocksRepositoryMockReserveResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmReserve *mStocksRepositoryMockReserve) Optional() *mStocksRepositoryMockReserve {
	mmReserve.optional = true
	return mmReserve
}

// Expect sets up expected params for StocksRepository.Reserve
func (mmReserve *mStocksRepositoryMockReserve) Expect(ctx context.Context, items []domain.Item) *mStocksRepositoryMockReserve {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Set")
	}

	if mmReserve.defaultExpectation == nil {
		mmReserve.defaultExpectation = &StocksRepositoryMockReserveExpectation{}
	}

	if mmReserve.defaultExpectation.paramPtrs != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by ExpectParams functions")
	}

	mmReserve.defaultExpectation.params = &StocksRepositoryMockReserveParams{ctx, items}
	for _, e := range mmReserve.expectations {
		if minimock.Equal(e.params, mmReserve.defaultExpectation.params) {
			mmReserve.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReserve.defaultExpectation.params)
		}
	}

	return mmReserve
}

// ExpectCtxParam1 sets up expected param ctx for StocksRepository.Reserve
func (mmReserve *mStocksRepositoryMockReserve) ExpectCtxParam1(ctx context.Context) *mStocksRepositoryMockReserve {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Set")
	}

	if mmReserve.defaultExpectation == nil {
		mmReserve.defaultExpectation = &StocksRepositoryMockReserveExpectation{}
	}

	if mmReserve.defaultExpectation.params != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Expect")
	}

	if mmReserve.defaultExpectation.paramPtrs == nil {
		mmReserve.defaultExpectation.paramPtrs = &StocksRepositoryMockReserveParamPtrs{}
	}
	mmReserve.defaultExpectation.paramPtrs.ctx = &ctx

	return mmReserve
}

// ExpectItemsParam2 sets up expected param items for StocksRepository.Reserve
func (mmReserve *mStocksRepositoryMockReserve) ExpectItemsParam2(items []domain.Item) *mStocksRepositoryMockReserve {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Set")
	}

	if mmReserve.defaultExpectation == nil {
		mmReserve.defaultExpectation = &StocksRepositoryMockReserveExpectation{}
	}

	if mmReserve.defaultExpectation.params != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Expect")
	}

	if mmReserve.defaultExpectation.paramPtrs == nil {
		mmReserve.defaultExpectation.paramPtrs = &StocksRepositoryMockReserveParamPtrs{}
	}
	mmReserve.defaultExpectation.paramPtrs.items = &items

	return mmReserve
}

// Inspect accepts an inspector function that has same arguments as the StocksRepository.Reserve
func (mmReserve *mStocksRepositoryMockReserve) Inspect(f func(ctx context.Context, items []domain.Item)) *mStocksRepositoryMockReserve {
	if mmReserve.mock.inspectFuncReserve != nil {
		mmReserve.mock.t.Fatalf("Inspect function is already set for StocksRepositoryMock.Reserve")
	}

	mmReserve.mock.inspectFuncReserve = f

	return mmReserve
}

// Return sets up results that will be returned by StocksRepository.Reserve
func (mmReserve *mStocksRepositoryMockReserve) Return(err error) *StocksRepositoryMock {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Set")
	}

	if mmReserve.defaultExpectation == nil {
		mmReserve.defaultExpectation = &StocksRepositoryMockReserveExpectation{mock: mmReserve.mock}
	}
	mmReserve.defaultExpectation.results = &StocksRepositoryMockReserveResults{err}
	return mmReserve.mock
}

// Set uses given function f to mock the StocksRepository.Reserve method
func (mmReserve *mStocksRepositoryMockReserve) Set(f func(ctx context.Context, items []domain.Item) (err error)) *StocksRepositoryMock {
	if mmReserve.defaultExpectation != nil {
		mmReserve.mock.t.Fatalf("Default expectation is already set for the StocksRepository.Reserve method")
	}

	if len(mmReserve.expectations) > 0 {
		mmReserve.mock.t.Fatalf("Some expectations are already set for the StocksRepository.Reserve method")
	}

	mmReserve.mock.funcReserve = f
	return mmReserve.mock
}

// When sets expectation for the StocksRepository.Reserve which will trigger the result defined by the following
// Then helper
func (mmReserve *mStocksRepositoryMockReserve) When(ctx context.Context, items []domain.Item) *StocksRepositoryMockReserveExpectation {
	if mmReserve.mock.funcReserve != nil {
		mmReserve.mock.t.Fatalf("StocksRepositoryMock.Reserve mock is already set by Set")
	}

	expectation := &StocksRepositoryMockReserveExpectation{
		mock:   mmReserve.mock,
		params: &StocksRepositoryMockReserveParams{ctx, items},
	}
	mmReserve.expectations = append(mmReserve.expectations, expectation)
	return expectation
}

// Then sets up StocksRepository.Reserve return parameters for the expectation previously defined by the When method
func (e *StocksRepositoryMockReserveExpectation) Then(err error) *StocksRepositoryMock {
	e.results = &StocksRepositoryMockReserveResults{err}
	return e.mock
}

// Times sets number of times StocksRepository.Reserve should be invoked
func (mmReserve *mStocksRepositoryMockReserve) Times(n uint64) *mStocksRepositoryMockReserve {
	if n == 0 {
		mmReserve.mock.t.Fatalf("Times of StocksRepositoryMock.Reserve mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmReserve.expectedInvocations, n)
	return mmReserve
}

func (mmReserve *mStocksRepositoryMockReserve) invocationsDone() bool {
	if len(mmReserve.expectations) == 0 && mmReserve.defaultExpectation == nil && mmReserve.mock.funcReserve == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmReserve.mock.afterReserveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmReserve.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Reserve implements lomsusecase.StocksRepository
func (mmReserve *StocksRepositoryMock) Reserve(ctx context.Context, items []domain.Item) (err error) {
	mm_atomic.AddUint64(&mmReserve.beforeReserveCounter, 1)
	defer mm_atomic.AddUint64(&mmReserve.afterReserveCounter, 1)

	if mmReserve.inspectFuncReserve != nil {
		mmReserve.inspectFuncReserve(ctx, items)
	}

	mm_params := StocksRepositoryMockReserveParams{ctx, items}

	// Record call args
	mmReserve.ReserveMock.mutex.Lock()
	mmReserve.ReserveMock.callArgs = append(mmReserve.ReserveMock.callArgs, &mm_params)
	mmReserve.ReserveMock.mutex.Unlock()

	for _, e := range mmReserve.ReserveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmReserve.ReserveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReserve.ReserveMock.defaultExpectation.Counter, 1)
		mm_want := mmReserve.ReserveMock.defaultExpectation.params
		mm_want_ptrs := mmReserve.ReserveMock.defaultExpectation.paramPtrs

		mm_got := StocksRepositoryMockReserveParams{ctx, items}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmReserve.t.Errorf("StocksRepositoryMock.Reserve got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.items != nil && !minimock.Equal(*mm_want_ptrs.items, mm_got.items) {
				mmReserve.t.Errorf("StocksRepositoryMock.Reserve got unexpected parameter items, want: %#v, got: %#v%s\n", *mm_want_ptrs.items, mm_got.items, minimock.Diff(*mm_want_ptrs.items, mm_got.items))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReserve.t.Errorf("StocksRepositoryMock.Reserve got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReserve.ReserveMock.defaultExpectation.results
		if mm_results == nil {
			mmReserve.t.Fatal("No results are set for the StocksRepositoryMock.Reserve")
		}
		return (*mm_results).err
	}
	if mmReserve.funcReserve != nil {
		return mmReserve.funcReserve(ctx, items)
	}
	mmReserve.t.Fatalf("Unexpected call to StocksRepositoryMock.Reserve. %v %v", ctx, items)
	return
}

// ReserveAfterCounter returns a count of finished StocksRepositoryMock.Reserve invocations
func (mmReserve *StocksRepositoryMock) ReserveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserve.afterReserveCounter)
}

// ReserveBeforeCounter returns a count of StocksRepositoryMock.Reserve invocations
func (mmReserve *StocksRepositoryMock) ReserveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserve.beforeReserveCounter)
}

// Calls returns a list of arguments used in each call to StocksRepositoryMock.Reserve.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReserve *mStocksRepositoryMockReserve) Calls() []*StocksRepositoryMockReserveParams {
	mmReserve.mutex.RLock()

	argCopy := make([]*StocksRepositoryMockReserveParams, len(mmReserve.callArgs))
	copy(argCopy, mmReserve.callArgs)

	mmReserve.mutex.RUnlock()

	return argCopy
}

// MinimockReserveDone returns true if the count of the Reserve invocations corresponds
// the number of defined expectations
func (m *StocksRepositoryMock) MinimockReserveDone() bool {
	if m.ReserveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ReserveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ReserveMock.invocationsDone()
}

// MinimockReserveInspect logs each unmet expectation
func (m *StocksRepositoryMock) MinimockReserveInspect() {
	for _, e := range m.ReserveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StocksRepositoryMock.Reserve with params: %#v", *e.params)
		}
	}

	afterReserveCounter := mm_atomic.LoadUint64(&m.afterReserveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ReserveMock.defaultExpectation != nil && afterReserveCounter < 1 {
		if m.ReserveMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StocksRepositoryMock.Reserve")
		} else {
			m.t.Errorf("Expected call to StocksRepositoryMock.Reserve with params: %#v", *m.ReserveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReserve != nil && afterReserveCounter < 1 {
		m.t.Error("Expected call to StocksRepositoryMock.Reserve")
	}

	if !m.ReserveMock.invocationsDone() && afterReserveCounter > 0 {
		m.t.Errorf("Expected %d calls to StocksRepositoryMock.Reserve but found %d calls",
			mm_atomic.LoadUint64(&m.ReserveMock.expectedInvocations), afterReserveCounter)
	}
}

type mStocksRepositoryMockReserveCancel struct {
	optional           bool
	mock               *StocksRepositoryMock
	defaultExpectation *StocksRepositoryMockReserveCancelExpectation
	expectations       []*StocksRepositoryMockReserveCancelExpectation

	callArgs []*StocksRepositoryMockReserveCancelParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// StocksRepositoryMockReserveCancelExpectation specifies expectation struct of the StocksRepository.ReserveCancel
type StocksRepositoryMockReserveCancelExpectation struct {
	mock      *StocksRepositoryMock
	params    *StocksRepositoryMockReserveCancelParams
	paramPtrs *StocksRepositoryMockReserveCancelParamPtrs
	results   *StocksRepositoryMockReserveCancelResults
	Counter   uint64
}

// StocksRepositoryMockReserveCancelParams contains parameters of the StocksRepository.ReserveCancel
type StocksRepositoryMockReserveCancelParams struct {
	ctx   context.Context
	items []domain.Item
}

// StocksRepositoryMockReserveCancelParamPtrs contains pointers to parameters of the StocksRepository.ReserveCancel
type StocksRepositoryMockReserveCancelParamPtrs struct {
	ctx   *context.Context
	items *[]domain.Item
}

// StocksRepositoryMockReserveCancelResults contains results of the StocksRepository.ReserveCancel
type StocksRepositoryMockReserveCancelResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Optional() *mStocksRepositoryMockReserveCancel {
	mmReserveCancel.optional = true
	return mmReserveCancel
}

// Expect sets up expected params for StocksRepository.ReserveCancel
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Expect(ctx context.Context, items []domain.Item) *mStocksRepositoryMockReserveCancel {
	if mmReserveCancel.mock.funcReserveCancel != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Set")
	}

	if mmReserveCancel.defaultExpectation == nil {
		mmReserveCancel.defaultExpectation = &StocksRepositoryMockReserveCancelExpectation{}
	}

	if mmReserveCancel.defaultExpectation.paramPtrs != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by ExpectParams functions")
	}

	mmReserveCancel.defaultExpectation.params = &StocksRepositoryMockReserveCancelParams{ctx, items}
	for _, e := range mmReserveCancel.expectations {
		if minimock.Equal(e.params, mmReserveCancel.defaultExpectation.params) {
			mmReserveCancel.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReserveCancel.defaultExpectation.params)
		}
	}

	return mmReserveCancel
}

// ExpectCtxParam1 sets up expected param ctx for StocksRepository.ReserveCancel
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) ExpectCtxParam1(ctx context.Context) *mStocksRepositoryMockReserveCancel {
	if mmReserveCancel.mock.funcReserveCancel != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Set")
	}

	if mmReserveCancel.defaultExpectation == nil {
		mmReserveCancel.defaultExpectation = &StocksRepositoryMockReserveCancelExpectation{}
	}

	if mmReserveCancel.defaultExpectation.params != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Expect")
	}

	if mmReserveCancel.defaultExpectation.paramPtrs == nil {
		mmReserveCancel.defaultExpectation.paramPtrs = &StocksRepositoryMockReserveCancelParamPtrs{}
	}
	mmReserveCancel.defaultExpectation.paramPtrs.ctx = &ctx

	return mmReserveCancel
}

// ExpectItemsParam2 sets up expected param items for StocksRepository.ReserveCancel
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) ExpectItemsParam2(items []domain.Item) *mStocksRepositoryMockReserveCancel {
	if mmReserveCancel.mock.funcReserveCancel != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Set")
	}

	if mmReserveCancel.defaultExpectation == nil {
		mmReserveCancel.defaultExpectation = &StocksRepositoryMockReserveCancelExpectation{}
	}

	if mmReserveCancel.defaultExpectation.params != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Expect")
	}

	if mmReserveCancel.defaultExpectation.paramPtrs == nil {
		mmReserveCancel.defaultExpectation.paramPtrs = &StocksRepositoryMockReserveCancelParamPtrs{}
	}
	mmReserveCancel.defaultExpectation.paramPtrs.items = &items

	return mmReserveCancel
}

// Inspect accepts an inspector function that has same arguments as the StocksRepository.ReserveCancel
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Inspect(f func(ctx context.Context, items []domain.Item)) *mStocksRepositoryMockReserveCancel {
	if mmReserveCancel.mock.inspectFuncReserveCancel != nil {
		mmReserveCancel.mock.t.Fatalf("Inspect function is already set for StocksRepositoryMock.ReserveCancel")
	}

	mmReserveCancel.mock.inspectFuncReserveCancel = f

	return mmReserveCancel
}

// Return sets up results that will be returned by StocksRepository.ReserveCancel
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Return(err error) *StocksRepositoryMock {
	if mmReserveCancel.mock.funcReserveCancel != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Set")
	}

	if mmReserveCancel.defaultExpectation == nil {
		mmReserveCancel.defaultExpectation = &StocksRepositoryMockReserveCancelExpectation{mock: mmReserveCancel.mock}
	}
	mmReserveCancel.defaultExpectation.results = &StocksRepositoryMockReserveCancelResults{err}
	return mmReserveCancel.mock
}

// Set uses given function f to mock the StocksRepository.ReserveCancel method
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Set(f func(ctx context.Context, items []domain.Item) (err error)) *StocksRepositoryMock {
	if mmReserveCancel.defaultExpectation != nil {
		mmReserveCancel.mock.t.Fatalf("Default expectation is already set for the StocksRepository.ReserveCancel method")
	}

	if len(mmReserveCancel.expectations) > 0 {
		mmReserveCancel.mock.t.Fatalf("Some expectations are already set for the StocksRepository.ReserveCancel method")
	}

	mmReserveCancel.mock.funcReserveCancel = f
	return mmReserveCancel.mock
}

// When sets expectation for the StocksRepository.ReserveCancel which will trigger the result defined by the following
// Then helper
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) When(ctx context.Context, items []domain.Item) *StocksRepositoryMockReserveCancelExpectation {
	if mmReserveCancel.mock.funcReserveCancel != nil {
		mmReserveCancel.mock.t.Fatalf("StocksRepositoryMock.ReserveCancel mock is already set by Set")
	}

	expectation := &StocksRepositoryMockReserveCancelExpectation{
		mock:   mmReserveCancel.mock,
		params: &StocksRepositoryMockReserveCancelParams{ctx, items},
	}
	mmReserveCancel.expectations = append(mmReserveCancel.expectations, expectation)
	return expectation
}

// Then sets up StocksRepository.ReserveCancel return parameters for the expectation previously defined by the When method
func (e *StocksRepositoryMockReserveCancelExpectation) Then(err error) *StocksRepositoryMock {
	e.results = &StocksRepositoryMockReserveCancelResults{err}
	return e.mock
}

// Times sets number of times StocksRepository.ReserveCancel should be invoked
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Times(n uint64) *mStocksRepositoryMockReserveCancel {
	if n == 0 {
		mmReserveCancel.mock.t.Fatalf("Times of StocksRepositoryMock.ReserveCancel mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmReserveCancel.expectedInvocations, n)
	return mmReserveCancel
}

func (mmReserveCancel *mStocksRepositoryMockReserveCancel) invocationsDone() bool {
	if len(mmReserveCancel.expectations) == 0 && mmReserveCancel.defaultExpectation == nil && mmReserveCancel.mock.funcReserveCancel == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmReserveCancel.mock.afterReserveCancelCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmReserveCancel.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ReserveCancel implements lomsusecase.StocksRepository
func (mmReserveCancel *StocksRepositoryMock) ReserveCancel(ctx context.Context, items []domain.Item) (err error) {
	mm_atomic.AddUint64(&mmReserveCancel.beforeReserveCancelCounter, 1)
	defer mm_atomic.AddUint64(&mmReserveCancel.afterReserveCancelCounter, 1)

	if mmReserveCancel.inspectFuncReserveCancel != nil {
		mmReserveCancel.inspectFuncReserveCancel(ctx, items)
	}

	mm_params := StocksRepositoryMockReserveCancelParams{ctx, items}

	// Record call args
	mmReserveCancel.ReserveCancelMock.mutex.Lock()
	mmReserveCancel.ReserveCancelMock.callArgs = append(mmReserveCancel.ReserveCancelMock.callArgs, &mm_params)
	mmReserveCancel.ReserveCancelMock.mutex.Unlock()

	for _, e := range mmReserveCancel.ReserveCancelMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmReserveCancel.ReserveCancelMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReserveCancel.ReserveCancelMock.defaultExpectation.Counter, 1)
		mm_want := mmReserveCancel.ReserveCancelMock.defaultExpectation.params
		mm_want_ptrs := mmReserveCancel.ReserveCancelMock.defaultExpectation.paramPtrs

		mm_got := StocksRepositoryMockReserveCancelParams{ctx, items}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmReserveCancel.t.Errorf("StocksRepositoryMock.ReserveCancel got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.items != nil && !minimock.Equal(*mm_want_ptrs.items, mm_got.items) {
				mmReserveCancel.t.Errorf("StocksRepositoryMock.ReserveCancel got unexpected parameter items, want: %#v, got: %#v%s\n", *mm_want_ptrs.items, mm_got.items, minimock.Diff(*mm_want_ptrs.items, mm_got.items))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReserveCancel.t.Errorf("StocksRepositoryMock.ReserveCancel got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReserveCancel.ReserveCancelMock.defaultExpectation.results
		if mm_results == nil {
			mmReserveCancel.t.Fatal("No results are set for the StocksRepositoryMock.ReserveCancel")
		}
		return (*mm_results).err
	}
	if mmReserveCancel.funcReserveCancel != nil {
		return mmReserveCancel.funcReserveCancel(ctx, items)
	}
	mmReserveCancel.t.Fatalf("Unexpected call to StocksRepositoryMock.ReserveCancel. %v %v", ctx, items)
	return
}

// ReserveCancelAfterCounter returns a count of finished StocksRepositoryMock.ReserveCancel invocations
func (mmReserveCancel *StocksRepositoryMock) ReserveCancelAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserveCancel.afterReserveCancelCounter)
}

// ReserveCancelBeforeCounter returns a count of StocksRepositoryMock.ReserveCancel invocations
func (mmReserveCancel *StocksRepositoryMock) ReserveCancelBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserveCancel.beforeReserveCancelCounter)
}

// Calls returns a list of arguments used in each call to StocksRepositoryMock.ReserveCancel.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReserveCancel *mStocksRepositoryMockReserveCancel) Calls() []*StocksRepositoryMockReserveCancelParams {
	mmReserveCancel.mutex.RLock()

	argCopy := make([]*StocksRepositoryMockReserveCancelParams, len(mmReserveCancel.callArgs))
	copy(argCopy, mmReserveCancel.callArgs)

	mmReserveCancel.mutex.RUnlock()

	return argCopy
}

// MinimockReserveCancelDone returns true if the count of the ReserveCancel invocations corresponds
// the number of defined expectations
func (m *StocksRepositoryMock) MinimockReserveCancelDone() bool {
	if m.ReserveCancelMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ReserveCancelMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ReserveCancelMock.invocationsDone()
}

// MinimockReserveCancelInspect logs each unmet expectation
func (m *StocksRepositoryMock) MinimockReserveCancelInspect() {
	for _, e := range m.ReserveCancelMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StocksRepositoryMock.ReserveCancel with params: %#v", *e.params)
		}
	}

	afterReserveCancelCounter := mm_atomic.LoadUint64(&m.afterReserveCancelCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ReserveCancelMock.defaultExpectation != nil && afterReserveCancelCounter < 1 {
		if m.ReserveCancelMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StocksRepositoryMock.ReserveCancel")
		} else {
			m.t.Errorf("Expected call to StocksRepositoryMock.ReserveCancel with params: %#v", *m.ReserveCancelMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReserveCancel != nil && afterReserveCancelCounter < 1 {
		m.t.Error("Expected call to StocksRepositoryMock.ReserveCancel")
	}

	if !m.ReserveCancelMock.invocationsDone() && afterReserveCancelCounter > 0 {
		m.t.Errorf("Expected %d calls to StocksRepositoryMock.ReserveCancel but found %d calls",
			mm_atomic.LoadUint64(&m.ReserveCancelMock.expectedInvocations), afterReserveCancelCounter)
	}
}

type mStocksRepositoryMockReserveRemove struct {
	optional           bool
	mock               *StocksRepositoryMock
	defaultExpectation *StocksRepositoryMockReserveRemoveExpectation
	expectations       []*StocksRepositoryMockReserveRemoveExpectation

	callArgs []*StocksRepositoryMockReserveRemoveParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// StocksRepositoryMockReserveRemoveExpectation specifies expectation struct of the StocksRepository.ReserveRemove
type StocksRepositoryMockReserveRemoveExpectation struct {
	mock      *StocksRepositoryMock
	params    *StocksRepositoryMockReserveRemoveParams
	paramPtrs *StocksRepositoryMockReserveRemoveParamPtrs
	results   *StocksRepositoryMockReserveRemoveResults
	Counter   uint64
}

// StocksRepositoryMockReserveRemoveParams contains parameters of the StocksRepository.ReserveRemove
type StocksRepositoryMockReserveRemoveParams struct {
	ctx   context.Context
	items []domain.Item
}

// StocksRepositoryMockReserveRemoveParamPtrs contains pointers to parameters of the StocksRepository.ReserveRemove
type StocksRepositoryMockReserveRemoveParamPtrs struct {
	ctx   *context.Context
	items *[]domain.Item
}

// StocksRepositoryMockReserveRemoveResults contains results of the StocksRepository.ReserveRemove
type StocksRepositoryMockReserveRemoveResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option by default unless you really need it, as it helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Optional() *mStocksRepositoryMockReserveRemove {
	mmReserveRemove.optional = true
	return mmReserveRemove
}

// Expect sets up expected params for StocksRepository.ReserveRemove
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Expect(ctx context.Context, items []domain.Item) *mStocksRepositoryMockReserveRemove {
	if mmReserveRemove.mock.funcReserveRemove != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Set")
	}

	if mmReserveRemove.defaultExpectation == nil {
		mmReserveRemove.defaultExpectation = &StocksRepositoryMockReserveRemoveExpectation{}
	}

	if mmReserveRemove.defaultExpectation.paramPtrs != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by ExpectParams functions")
	}

	mmReserveRemove.defaultExpectation.params = &StocksRepositoryMockReserveRemoveParams{ctx, items}
	for _, e := range mmReserveRemove.expectations {
		if minimock.Equal(e.params, mmReserveRemove.defaultExpectation.params) {
			mmReserveRemove.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmReserveRemove.defaultExpectation.params)
		}
	}

	return mmReserveRemove
}

// ExpectCtxParam1 sets up expected param ctx for StocksRepository.ReserveRemove
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) ExpectCtxParam1(ctx context.Context) *mStocksRepositoryMockReserveRemove {
	if mmReserveRemove.mock.funcReserveRemove != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Set")
	}

	if mmReserveRemove.defaultExpectation == nil {
		mmReserveRemove.defaultExpectation = &StocksRepositoryMockReserveRemoveExpectation{}
	}

	if mmReserveRemove.defaultExpectation.params != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Expect")
	}

	if mmReserveRemove.defaultExpectation.paramPtrs == nil {
		mmReserveRemove.defaultExpectation.paramPtrs = &StocksRepositoryMockReserveRemoveParamPtrs{}
	}
	mmReserveRemove.defaultExpectation.paramPtrs.ctx = &ctx

	return mmReserveRemove
}

// ExpectItemsParam2 sets up expected param items for StocksRepository.ReserveRemove
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) ExpectItemsParam2(items []domain.Item) *mStocksRepositoryMockReserveRemove {
	if mmReserveRemove.mock.funcReserveRemove != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Set")
	}

	if mmReserveRemove.defaultExpectation == nil {
		mmReserveRemove.defaultExpectation = &StocksRepositoryMockReserveRemoveExpectation{}
	}

	if mmReserveRemove.defaultExpectation.params != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Expect")
	}

	if mmReserveRemove.defaultExpectation.paramPtrs == nil {
		mmReserveRemove.defaultExpectation.paramPtrs = &StocksRepositoryMockReserveRemoveParamPtrs{}
	}
	mmReserveRemove.defaultExpectation.paramPtrs.items = &items

	return mmReserveRemove
}

// Inspect accepts an inspector function that has same arguments as the StocksRepository.ReserveRemove
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Inspect(f func(ctx context.Context, items []domain.Item)) *mStocksRepositoryMockReserveRemove {
	if mmReserveRemove.mock.inspectFuncReserveRemove != nil {
		mmReserveRemove.mock.t.Fatalf("Inspect function is already set for StocksRepositoryMock.ReserveRemove")
	}

	mmReserveRemove.mock.inspectFuncReserveRemove = f

	return mmReserveRemove
}

// Return sets up results that will be returned by StocksRepository.ReserveRemove
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Return(err error) *StocksRepositoryMock {
	if mmReserveRemove.mock.funcReserveRemove != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Set")
	}

	if mmReserveRemove.defaultExpectation == nil {
		mmReserveRemove.defaultExpectation = &StocksRepositoryMockReserveRemoveExpectation{mock: mmReserveRemove.mock}
	}
	mmReserveRemove.defaultExpectation.results = &StocksRepositoryMockReserveRemoveResults{err}
	return mmReserveRemove.mock
}

// Set uses given function f to mock the StocksRepository.ReserveRemove method
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Set(f func(ctx context.Context, items []domain.Item) (err error)) *StocksRepositoryMock {
	if mmReserveRemove.defaultExpectation != nil {
		mmReserveRemove.mock.t.Fatalf("Default expectation is already set for the StocksRepository.ReserveRemove method")
	}

	if len(mmReserveRemove.expectations) > 0 {
		mmReserveRemove.mock.t.Fatalf("Some expectations are already set for the StocksRepository.ReserveRemove method")
	}

	mmReserveRemove.mock.funcReserveRemove = f
	return mmReserveRemove.mock
}

// When sets expectation for the StocksRepository.ReserveRemove which will trigger the result defined by the following
// Then helper
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) When(ctx context.Context, items []domain.Item) *StocksRepositoryMockReserveRemoveExpectation {
	if mmReserveRemove.mock.funcReserveRemove != nil {
		mmReserveRemove.mock.t.Fatalf("StocksRepositoryMock.ReserveRemove mock is already set by Set")
	}

	expectation := &StocksRepositoryMockReserveRemoveExpectation{
		mock:   mmReserveRemove.mock,
		params: &StocksRepositoryMockReserveRemoveParams{ctx, items},
	}
	mmReserveRemove.expectations = append(mmReserveRemove.expectations, expectation)
	return expectation
}

// Then sets up StocksRepository.ReserveRemove return parameters for the expectation previously defined by the When method
func (e *StocksRepositoryMockReserveRemoveExpectation) Then(err error) *StocksRepositoryMock {
	e.results = &StocksRepositoryMockReserveRemoveResults{err}
	return e.mock
}

// Times sets number of times StocksRepository.ReserveRemove should be invoked
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Times(n uint64) *mStocksRepositoryMockReserveRemove {
	if n == 0 {
		mmReserveRemove.mock.t.Fatalf("Times of StocksRepositoryMock.ReserveRemove mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmReserveRemove.expectedInvocations, n)
	return mmReserveRemove
}

func (mmReserveRemove *mStocksRepositoryMockReserveRemove) invocationsDone() bool {
	if len(mmReserveRemove.expectations) == 0 && mmReserveRemove.defaultExpectation == nil && mmReserveRemove.mock.funcReserveRemove == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmReserveRemove.mock.afterReserveRemoveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmReserveRemove.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ReserveRemove implements lomsusecase.StocksRepository
func (mmReserveRemove *StocksRepositoryMock) ReserveRemove(ctx context.Context, items []domain.Item) (err error) {
	mm_atomic.AddUint64(&mmReserveRemove.beforeReserveRemoveCounter, 1)
	defer mm_atomic.AddUint64(&mmReserveRemove.afterReserveRemoveCounter, 1)

	if mmReserveRemove.inspectFuncReserveRemove != nil {
		mmReserveRemove.inspectFuncReserveRemove(ctx, items)
	}

	mm_params := StocksRepositoryMockReserveRemoveParams{ctx, items}

	// Record call args
	mmReserveRemove.ReserveRemoveMock.mutex.Lock()
	mmReserveRemove.ReserveRemoveMock.callArgs = append(mmReserveRemove.ReserveRemoveMock.callArgs, &mm_params)
	mmReserveRemove.ReserveRemoveMock.mutex.Unlock()

	for _, e := range mmReserveRemove.ReserveRemoveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmReserveRemove.ReserveRemoveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReserveRemove.ReserveRemoveMock.defaultExpectation.Counter, 1)
		mm_want := mmReserveRemove.ReserveRemoveMock.defaultExpectation.params
		mm_want_ptrs := mmReserveRemove.ReserveRemoveMock.defaultExpectation.paramPtrs

		mm_got := StocksRepositoryMockReserveRemoveParams{ctx, items}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmReserveRemove.t.Errorf("StocksRepositoryMock.ReserveRemove got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.items != nil && !minimock.Equal(*mm_want_ptrs.items, mm_got.items) {
				mmReserveRemove.t.Errorf("StocksRepositoryMock.ReserveRemove got unexpected parameter items, want: %#v, got: %#v%s\n", *mm_want_ptrs.items, mm_got.items, minimock.Diff(*mm_want_ptrs.items, mm_got.items))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmReserveRemove.t.Errorf("StocksRepositoryMock.ReserveRemove got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmReserveRemove.ReserveRemoveMock.defaultExpectation.results
		if mm_results == nil {
			mmReserveRemove.t.Fatal("No results are set for the StocksRepositoryMock.ReserveRemove")
		}
		return (*mm_results).err
	}
	if mmReserveRemove.funcReserveRemove != nil {
		return mmReserveRemove.funcReserveRemove(ctx, items)
	}
	mmReserveRemove.t.Fatalf("Unexpected call to StocksRepositoryMock.ReserveRemove. %v %v", ctx, items)
	return
}

// ReserveRemoveAfterCounter returns a count of finished StocksRepositoryMock.ReserveRemove invocations
func (mmReserveRemove *StocksRepositoryMock) ReserveRemoveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserveRemove.afterReserveRemoveCounter)
}

// ReserveRemoveBeforeCounter returns a count of StocksRepositoryMock.ReserveRemove invocations
func (mmReserveRemove *StocksRepositoryMock) ReserveRemoveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReserveRemove.beforeReserveRemoveCounter)
}

// Calls returns a list of arguments used in each call to StocksRepositoryMock.ReserveRemove.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmReserveRemove *mStocksRepositoryMockReserveRemove) Calls() []*StocksRepositoryMockReserveRemoveParams {
	mmReserveRemove.mutex.RLock()

	argCopy := make([]*StocksRepositoryMockReserveRemoveParams, len(mmReserveRemove.callArgs))
	copy(argCopy, mmReserveRemove.callArgs)

	mmReserveRemove.mutex.RUnlock()

	return argCopy
}

// MinimockReserveRemoveDone returns true if the count of the ReserveRemove invocations corresponds
// the number of defined expectations
func (m *StocksRepositoryMock) MinimockReserveRemoveDone() bool {
	if m.ReserveRemoveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ReserveRemoveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ReserveRemoveMock.invocationsDone()
}

// MinimockReserveRemoveInspect logs each unmet expectation
func (m *StocksRepositoryMock) MinimockReserveRemoveInspect() {
	for _, e := range m.ReserveRemoveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StocksRepositoryMock.ReserveRemove with params: %#v", *e.params)
		}
	}

	afterReserveRemoveCounter := mm_atomic.LoadUint64(&m.afterReserveRemoveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ReserveRemoveMock.defaultExpectation != nil && afterReserveRemoveCounter < 1 {
		if m.ReserveRemoveMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to StocksRepositoryMock.ReserveRemove")
		} else {
			m.t.Errorf("Expected call to StocksRepositoryMock.ReserveRemove with params: %#v", *m.ReserveRemoveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReserveRemove != nil && afterReserveRemoveCounter < 1 {
		m.t.Error("Expected call to StocksRepositoryMock.ReserveRemove")
	}

	if !m.ReserveRemoveMock.invocationsDone() && afterReserveRemoveCounter > 0 {
		m.t.Errorf("Expected %d calls to StocksRepositoryMock.ReserveRemove but found %d calls",
			mm_atomic.LoadUint64(&m.ReserveRemoveMock.expectedInvocations), afterReserveRemoveCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StocksRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetBySKUInspect()

			m.MinimockReserveInspect()

			m.MinimockReserveCancelInspect()

			m.MinimockReserveRemoveInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StocksRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StocksRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetBySKUDone() &&
		m.MinimockReserveDone() &&
		m.MinimockReserveCancelDone() &&
		m.MinimockReserveRemoveDone()
}
